dubbo:
  application:
    name: demo-provider
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: xyz.wenjiesx.framework.dubbo.demo.provider

---
dubbo:
  registry:
    address: N/A
spring:
  profiles: default
#  scan:
#    base-packages: xyz.wenjiesx.framework.dubbo.demo.provider

---
spring:
  profiles: zookeeper

dubbo:
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
  metadata-report:
    address: redis://127.0.0.1:6379
