dubbo:
  application:
    name: demo-consumer
server:
  port: 8082

---
spring:
  profiles: zookeeper

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: redis://127.0.0.1:6379